[v0.4.0]: Added DNF package manager support.
Signed-off-by: Chris1320 <chris1320is@protonmail.com>

diff --git a/install b/install
--- a/install
+++ b/install
@@ -6,17 +6,22 @@
 # To disable changing the default shell and opening ZSH, run with `--install-only` flag.
 
 name="SetupGuides Custom ZSH"
-version=(0 3 0)
+version=(0 4 0)
 title="${name} v${version[*]:0:1}.${version[*]:1:1}.${version[*]:2:1}"
 omz_installation="$HOME/.oh-my-zsh"
 
-# Detect if the user uses pacman instead of apt.
-if [[ -f "/usr/bin/pacman" ]]; then
-    echo "[i] Using \`pacman\` instead of \`apt\`."
-    pacman=true
+# Detect the user's package manager.
+if [[ -f "$(command -v pacman)" ]]; then package_manager="pacman"
+elif [[ -f "$(command -v dnf)" ]]; then package_manager="dnf"
+elif [[ -f "$(command -v apt)" ]]; then package_manager="apt"
 else
-    pacman=false
+    echo "[E] Unable to automatically detect your package manager."
+    echo "[E] Please consider manually installing the customization instead."
+    echo "[E] Exiting..."
+    exit 127
 fi
+
+echo "[i] Detected package manager: ${package_manager}"
 
 echo "$title"
 echo
@@ -29,17 +34,21 @@ if [[ "$EUID" -eq 0 ]]; then
 fi
 
 # Check if the script is running on Termux.
-if [[ $PREFIX = *"com.termux"* ]]; then
-    sudocmd=""  # No need for sudo on Termux.
-else
-    sudocmd="sudo"
+# $PREFIX is an envvar in Termux that contains the system filepath.
+if [[ $PREFIX = *"com.termux"* ]]; then sudocmd=""  # No need for sudo on Termux since we don't need root to install pkgs.
+else sudocmd="sudo"
 fi
 
 printf "[i] Installing zsh, wget, and git...\n\n"
-if [[ $pacman = true ]]; then
-    ${sudocmd} pacman -Syu --noconfirm zsh wget git
+pkgs_to_install="zsh wget git"
+if [[ $package_manager = "pacman" ]]; then ${sudocmd} pacman -Syu --noconfirm ${pkgs_to_install}
+elif [[ $package_manager = "dnf" ]]; then ${sudocmd} dnf install -y ${pkgs_to_install} util-linux-user  # util-linux-user provides chsh
+elif [[ $package_manager = "apt" ]]; then ${sudocmd} apt update -y && ${sudocmd} apt install -y --upgrade ${pkgs_to_install}
 else
-    ${sudocmd} apt update -y && ${sudocmd} apt install -y --upgrade zsh wget git
+    echo "[E] Unable to automatically detect your package manager."
+    echo "[E] Please consider manually installing the customization instead."
+    echo "[E] Exiting..."
+    exit 256
 fi
 
 if [[ $? -ne 0 ]]; then
