[WIP] Fixing chsh on Termux.
Signed-off-by: Chris1320 <chris1320is@protonmail.com>

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
 name="SetupGuides Custom ZSH"
-version=(0 1 2)
+version=(0 1 3)
 title="${name} v${version[@]:0:1}.${version[@]:1:1}.${version[@]:2:1}"
 omz_installation="$HOME/.oh-my-zsh"
 
@@ -70,14 +70,17 @@ echo 'export GPG_TTY=$TTY  # Fix GPG "gpg failed to sign data" error.' >> "${HOM
 printf "[i] Changing default shell to zsh...\n\n"
 if [[ $PREFIX = *"com.termux"* ]]; then
     chsh -s zsh
+    if [[ $? -ne 0 ]]; then
+        echo "[E] Failed to change default shell."
+        exit 6
+    fi
 
 else
     chsh -s $(command -v zsh)
-fi
-
-if [[ $? -ne 0 ]]; then
-    echo "[E] Failed to change shell."
-    exit 6
+    if [[ $? -ne 0 ]]; then
+        echo "[E] Failed to change default shell."
+        exit 7
+    fi
 fi
 
 echo
